accounts/urls.py
from django.urls import path

from .views import UserRegistrationView, LogoutView, UserLoginView


app_name = 'accounts'

urlpatterns = [
    path(
        "login/", UserLoginView.as_view(),
        name="user_login"
    ),
    path(
        "logout/", LogoutView.as_view(),
        name="user_logout"
    ),
    path(
        "register/", UserRegistrationView.as_view(),
        name="user_registration"
    ),
]

banking_system/urls.py
from django.contrib import admin
from django.urls import include, path

from core.views import HomeView


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path(
        'transactions/',
        include('transactions.urls', namespace='transactions')
    )
]

accounts/models.py
from decimal import Decimal

from django.contrib.auth.models import AbstractUser
from django.core.validators import (
    MinValueValidator,
    MaxValueValidator,
)
from django.db import models

from .constants import GENDER_CHOICE
from .managers import UserManager


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, null=False, blank=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    @property
    def balance(self):
        if hasattr(self, 'account'):
            return self.account.balance
        return 0


class BankAccountType(models.Model):
    name = models.CharField(max_length=128)
    maximum_withdrawal_amount = models.DecimalField(
        decimal_places=2,
        max_digits=12
    )
    annual_interest_rate = models.DecimalField(
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        decimal_places=2,
        max_digits=5,
        help_text='Interest rate from 0 - 100'
    )
    interest_calculation_per_year = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(12)],
        help_text='The number of times interest will be calculated per year'
    )

    def __str__(self):
        return self.name

    def calculate_interest(self, principal):
        """
        Calculate interest for each account type.

        This uses a basic interest calculation formula
        """
        p = principal
        r = self.annual_interest_rate
        n = Decimal(self.interest_calculation_per_year)

        # Basic Future Value formula to calculate interest
        interest = (p * (1 + ((r/100) / n))) - p

        return round(interest, 2)


class UserBankAccount(models.Model):
    user = models.OneToOneField(
        User,
        related_name='account',
        on_delete=models.CASCADE,
    )
    account_type = models.ForeignKey(
        BankAccountType,
        related_name='accounts',
        on_delete=models.CASCADE
    )
    account_no = models.PositiveIntegerField(unique=True)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICE)
    birth_date = models.DateField(null=True, blank=True)
    balance = models.DecimalField(
        default=0,
        max_digits=12,
        decimal_places=2
    )
    interest_start_date = models.DateField(
        null=True, blank=True,
        help_text=(
            'The month number that interest calculation will start from'
        )
    )
    initial_deposit_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return str(self.account_no)

    def get_interest_calculation_months(self):
        """
        List of month numbers for which the interest will be calculated

        returns [2, 4, 6, 8, 10, 12] for every 2 months interval
        """
        interval = int(
            12 / self.account_type.interest_calculation_per_year
        )
        start = self.interest_start_date.month
        return [i for i in range(start, 13, interval)]


class UserAddress(models.Model):
    user = models.OneToOneField(
        User,
        related_name='address',
        on_delete=models.CASCADE,
    )
    street_address = models.CharField(max_length=512)
    city = models.CharField(max_length=256)
    postal_code = models.PositiveIntegerField()
    country = models.CharField(max_length=256)

    def __str__(self):
        return self.user.email

accounts/forms.py
from django import forms
from django.conf import settings
from django.contrib.auth import authenticate, get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction

from .models import User, BankAccountType, UserBankAccount, UserAddress
from .constants import GENDER_CHOICE


class UserAddressForm(forms.ModelForm):

    class Meta:
        model = UserAddress
        fields = [
            'street_address',
            'city',
            'postal_code',
            'country'
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': (
                    'appearance-none block w-full bg-gray-200 '
                    'text-gray-700 border border-gray-200 rounded '
                    'py-3 px-4 leading-tight focus:outline-none '
                    'focus:bg-white focus:border-gray-500'
                )
            })

class CustomAuthenticationForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        super().__init__(*args, **kwargs)

    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')

        if email and password:
            UserModel = get_user_model()
            try:
                user = UserModel.objects.get(email=email)
            except UserModel.DoesNotExist:
                raise forms.ValidationError("This email is not registered.")

            self.user = authenticate(self.request, email=email, password=password)

            if self.user is None:
                raise forms.ValidationError("Invalid email or password.")

        return self.cleaned_data

    def get_user(self):
        return self.user



class UserRegistrationForm(UserCreationForm):
    account_type = forms.ModelChoiceField(
        queryset=BankAccountType.objects.all()
    )
    gender = forms.ChoiceField(choices=GENDER_CHOICE)
    birth_date = forms.DateField(widget=forms.DateInput(attrs={'type':'date'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'autofocus':'on'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'autofocus':'off'}))

    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': (
                    'appearance-none block w-full bg-gray-200 '
                    'text-gray-700 border border-gray-200 '
                    'rounded py-3 px-4 leading-tight '
                    'focus:outline-none focus:bg-white '
                    'focus:border-gray-500'
                )
            })

    @transaction.atomic
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
            account_type = self.cleaned_data.get('account_type')
            gender = self.cleaned_data.get('gender')
            birth_date = self.cleaned_data.get('birth_date')

            UserBankAccount.objects.create(
                user=user,
                gender=gender,
                birth_date=birth_date,
                account_type=account_type,
                account_no=(
                    user.id +
                    settings.ACCOUNT_NUMBER_START_FROM
                )
            )
        return user

accounts/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model, login, logout
from django.contrib.auth.views import LoginView
from django.shortcuts import HttpResponseRedirect, redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, RedirectView

from .forms import UserRegistrationForm, UserAddressForm, CustomAuthenticationForm

User = get_user_model()

class UserRegistrationView(TemplateView):
    model = User
    form_class = UserRegistrationForm
    template_name = 'accounts/user_registration.html'

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return HttpResponseRedirect(
                reverse_lazy('transactions:transaction_report')
            )
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        registration_form = UserRegistrationForm(self.request.POST)
        address_form = UserAddressForm(self.request.POST)

        if registration_form.is_valid() and address_form.is_valid():
            user = registration_form.save()
            address = address_form.save(commit=False)
            address.user = user
            address.save()

            login(self.request, user)
            messages.success(
                self.request,
                (
                    f'Thank You For Creating A Bank Account. '
                    f'Your Account Number is {user.account.account_no}.'
                )
            )
            return HttpResponseRedirect(
                reverse_lazy('transactions:deposit_money')
            )

        return self.render_to_response(
            self.get_context_data(
                registration_form=registration_form,
                address_form=address_form
            )
        )

    def get_context_data(self, **kwargs):
        if 'registration_form' not in kwargs:
            kwargs['registration_form'] = UserRegistrationForm()
        if 'address_form' not in kwargs:
            kwargs['address_form'] = UserAddressForm()
        return super().get_context_data(**kwargs)

class UserLoginView(LoginView):
    form_class = CustomAuthenticationForm
    template_name = 'accounts/user_login.html'
    redirect_authenticated_user = True

    def form_valid(self, form):
        user = form.get_user()
        if user is not None:
            login(self.request, user)
            return redirect(self.get_success_url())
        else:
            form.add_error(None, 'This email is not registered.')
            context = self.get_context_data(form=form)
            return self.render_to_response(context)

    def form_invalid(self, form):
        context = self.get_context_data(form=form)
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class LogoutView(RedirectView):
    pattern_name = 'home'

    def get_redirect_url(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            logout(self.request)
        return super().get_redirect_url(*args, **kwargs)

templates/accounts/user_login.html
{% extends 'core/base.html' %}
{% load static %}

{% block head_title %}Banking System{% endblock %}

{% block content %}
<div class="grid grid-cols-3 gap-4">
    <div></div>
    <div class="py-2 px-3 rounded-xl bg-white mt-12">
        <h1 class="font-mono font-bold text-3xl text-center pb-5 shadow-md">Sign In</h1>
        <hr>
        {% if form.non_field_errors %}
        <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mt-2" role="alert">
            <p class="font-bold">Error!</p>
            <ul>
                {% for error in form.non_field_errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        <div class="w-full mt-10">
            <form method="post" class="shadow-md border border-gray-200 rounded px-8 pt-6 pb-8 mb-4" autocomplete="off" id="login-form">
                {% csrf_token %}
                {% for hidden_field in form.hidden_fields %}
                    {{ hidden_field }}
                {% endfor %}
                {% for field in form.visible_fields %}
                <div class="mb-4">
                    <label for="{{ field.id_for_label }}" class="block text-gray-700 text-sm font-bold mb-2">{{ field.label }}</label>
                    <input
                        type="{{ field.field.widget.input_type }}"
                        id="{{ field.id_for_label }}"
                        name="{{ field.html_name }}_temp"
                        class="shadow appearance-none border {% if field.errors %} border-red-500 {% else %} border-gray-500 {% endif %} rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"

                        onfocus="this.setAttribute('autocomplete', '{{ field.html_name }}'); this.setAttribute('name', '{{ field.html_name }}');"
                    >
                    {% if field.errors %}
                    <p class="text-red-600 text-sm italic">{{ field.errors }}</p>
                    {% endif %}
                </div>
                {% endfor %}
                {% if form.non_field_errors and 'This email is not registered.' in form.non_field_errors %}
                    <p class="text-center text-sm text-gray-600 mt-4">Don't have an account? <a href="{% url 'accounts:user_registration' %}" class="text-blue-600">Register now</a></p>
                {% endif %}
                <div class="flex items-center justify-center w-full">
                    <button type="submit" class="bg-blue-900 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
                        Sign In
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/accounts/user_registration.html
{% extends 'core/base.html' %} {% load static %} {% block head_title %}Banking System{% endblock %} {% block content %} {% if registration_form.non_field_errors %} {% for error in registration_form.non_field_errors %}
<div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mt-2" role="alert">
    <p class="font-bold">Error!</p>
    <p class="block sm:inline">{{ error }}</p>
</div>
{% endfor %} {% endif %} {% if address_form.non_field_errors %} {% for error in address_form.non_field_errors %}
<div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mt-2" role="alert">
    <p class="font-bold">Error!</p>
    <p class="block sm:inline">{{ error }}</p>
</div>
{% endfor %} {% endif %}
<div class="bg-white px-3 py-4 rounded-xl">
    <h1 class="font-mono font-bold text-3xl text-center pb-5">Register</h1>
    <hr />
    <div class="w-full mt-10">
        <form method="post" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
            {% csrf_token %} {% for hidden_field in registration_form.hidden_fields %} {{ hidden_field.errors }} {{ hidden_field }} {% endfor %}
            <div class="flex flex-wrap -mx-3 mb-6">
                <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="{{ registration_form.first_name.id_for_label }}">
                        {{ registration_form.first_name.label }}
                    </label> {{ registration_form.first_name }} {% if registration_form.first_name.errors %} {% for error in registration_form.first_name.errors %}
                    <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                    {% endfor %} {% endif %}
                </div>
                <div class="w-full md:w-1/2 px-3">
                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="{{ registration_form.last_name.id_for_label }}">
                        {{ registration_form.last_name.label }}
                    </label> {{ registration_form.last_name }} {% if registration_form.last_name.errors %} {% for error in registration_form.last_name.errors %}
                    <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                    {% endfor %} {% endif %}
                </div>
            </div>
            <div class="flex flex-wrap -mx-3 mb-6">
                <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="{{ registration_form.email.id_for_label }}">
                        {{ registration_form.email.label }}
                    </label> {{ registration_form.email }} {% if registration_form.email.errors %} {% for error in registration_form.email.errors %}
                    <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                    {% endfor %} {% endif %}
                </div>
                <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="{{ registration_form.account_type.id_for_label }}">
                        {{ registration_form.account_type.label }}
                    </label> {{ registration_form.account_type }} {% if registration_form.account_type.errors %} {% for error in registration_form.account_type.errors %}
                    <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                    {% endfor %} {% endif %}
                </div>
            </div>
            <div class="flex flex-wrap -mx-3 mb-6">
                <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="{{ registration_form.gender.id_for_label }}">
                        {{ registration_form.gender.label }}
                    </label> {{ registration_form.gender }} {% if registration_form.gender.errors %} {% for error in registration_form.gender.errors %}
                    <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                    {% endfor %} {% endif %}
                </div>
                <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="{{ registration_form.birth_date.id_for_label }}">
                        {{ registration_form.birth_date.label }}
                    </label> {{ registration_form.birth_date }} {% if registration_form.birth_date.errors %} {% for error in registration_form.birth_date.errors %}
                    <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                    {% endfor %} {% endif %}
                </div>
            </div>
            <div class="flex flex-wrap -mx-3 mb-6">
                <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="{{ registration_form.password1.id_for_label }}">
                        {{ registration_form.password1.label }}
                    </label> {{ registration_form.password1 }} {% if registration_form.password1.errors %} {% for error in registration_form.password1.errors %}
                    <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                    {% endfor %} {% endif %}
                </div>
                <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="{{ registration_form.password2.id_for_label }}">
                        {{ registration_form.password2.label }}
                    </label> {{ registration_form.password2 }} {% if registration_form.password2.errors %} {% for error in registration_form.password2.errors %}
                    <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                    {% endfor %} {% endif %}
                </div>
            </div>

            {% for hidden_field in address_form.hidden_fields %} {{ hidden_field.errors }} {{ hidden_field }} {% endfor %}
            <div class="flex flex-wrap -mx-3 mb-6">
                <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="{{ address_form.street_address.id_for_label }}">
                        {{ address_form.street_address.label }}
                    </label> {{ address_form.street_address }} {% if address_form.street_address.errors %} {% for error in address_form.street_address.errors %}
                    <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                    {% endfor %} {% endif %}
                </div>
                <div class="w-full md:w-1/2 px-3">
                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="{{ address_form.city.id_for_label }}">
                        {{ address_form.city.label }}
                    </label> {{ address_form.city }} {% if address_form.city.errors %} {% for error in address_form.city.errors %}
                    <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                    {% endfor %} {% endif %}
                </div>
            </div>
            <div class="flex flex-wrap -mx-3 mb-6">
                <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="{{ address_form.postal_code.id_for_label }}">
                        {{ address_form.postal_code.label }}
                    </label> {{ address_form.postal_code }} {% if address_form.postal_code.errors %} {% for error in address_form.postal_code.errors %}
                    <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                    {% endfor %} {% endif %}
                </div>
                <div class="w-full md:w-1/2 px-3">
                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="{{ address_form.country.id_for_label }}">
                        {{ address_form.country.label }}
                    </label> {{ address_form.country }} {% if address_form.country.errors %} {% for error in address_form.country.errors %}
                    <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                    {% endfor %} {% endif %}
                </div>
            </div>
            <div class="flex items-center justify-between">
                <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                    Register
                </button>
            </div>
        </form>
    </div>
</div>
{% endblock %}